// Atmospheric Glass — generated by designmd. Do not edit.
// Source of truth: DESIGN.md

import SwiftUI

public enum Theme {
    public enum Colors {
        public static let surface = Color(.sRGB, red: 0.043, green: 0.075, blue: 0.149, opacity: 1)  // #0b1326
        public static let surfaceDim = Color(.sRGB, red: 0.043, green: 0.075, blue: 0.149, opacity: 1)  // #0b1326
        public static let surfaceBright = Color(.sRGB, red: 0.192, green: 0.224, blue: 0.302, opacity: 1)  // #31394d
        public static let surfaceContainerLowest = Color(.sRGB, red: 0.024, green: 0.055, blue: 0.125, opacity: 1)  // #060e20
        public static let surfaceContainerLow = Color(.sRGB, red: 0.075, green: 0.106, blue: 0.18, opacity: 1)  // #131b2e
        public static let surfaceContainer = Color(.sRGB, red: 0.09, green: 0.122, blue: 0.2, opacity: 1)  // #171f33
        public static let surfaceContainerHigh = Color(.sRGB, red: 0.133, green: 0.165, blue: 0.239, opacity: 1)  // #222a3d
        public static let surfaceContainerHighest = Color(.sRGB, red: 0.176, green: 0.204, blue: 0.286, opacity: 1)  // #2d3449
        public static let onSurface = Color(.sRGB, red: 0.855, green: 0.886, blue: 0.992, opacity: 1)  // #dae2fd
        public static let onSurfaceVariant = Color(.sRGB, red: 0.769, green: 0.78, blue: 0.784, opacity: 1)  // #c4c7c8
        public static let inverseSurface = Color(.sRGB, red: 0.855, green: 0.886, blue: 0.992, opacity: 1)  // #dae2fd
        public static let inverseOnSurface = Color(.sRGB, red: 0.157, green: 0.188, blue: 0.267, opacity: 1)  // #283044
        public static let outline = Color(.sRGB, red: 0.557, green: 0.569, blue: 0.573, opacity: 1)  // #8e9192
        public static let outlineVariant = Color(.sRGB, red: 0.267, green: 0.278, blue: 0.282, opacity: 1)  // #444748
        public static let surfaceTint = Color(.sRGB, red: 0.776, green: 0.776, blue: 0.78, opacity: 1)  // #c6c6c7
        public static let primary = Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1)  // #ffffff
        public static let onPrimary = Color(.sRGB, red: 0.184, green: 0.192, blue: 0.192, opacity: 1)  // #2f3131
        public static let primaryContainer = Color(.sRGB, red: 0.886, green: 0.886, blue: 0.886, opacity: 1)  // #e2e2e2
        public static let onPrimaryContainer = Color(.sRGB, red: 0.388, green: 0.396, blue: 0.396, opacity: 1)  // #636565
        public static let inversePrimary = Color(.sRGB, red: 0.365, green: 0.373, blue: 0.373, opacity: 1)  // #5d5f5f
        public static let secondary = Color(.sRGB, red: 0.678, green: 0.788, blue: 0.922, opacity: 1)  // #adc9eb
        public static let onSecondary = Color(.sRGB, red: 0.078, green: 0.196, blue: 0.306, opacity: 1)  // #14324e
        public static let secondaryContainer = Color(.sRGB, red: 0.188, green: 0.294, blue: 0.408, opacity: 1)  // #304b68
        public static let onSecondaryContainer = Color(.sRGB, red: 0.624, green: 0.733, blue: 0.867, opacity: 1)  // #9fbbdd
        public static let tertiary = Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1)  // #ffffff
        public static let onTertiary = Color(.sRGB, red: 0.384, green: 0, blue: 0.251, opacity: 1)  // #620040
        public static let tertiaryContainer = Color(.sRGB, red: 1, green: 0.847, blue: 0.906, opacity: 1)  // #ffd8e7
        public static let onTertiaryContainer = Color(.sRGB, red: 0.671, green: 0.216, blue: 0.475, opacity: 1)  // #ab3779
        public static let error = Color(.sRGB, red: 1, green: 0.706, blue: 0.671, opacity: 1)  // #ffb4ab
        public static let onError = Color(.sRGB, red: 0.412, green: 0, blue: 0.02, opacity: 1)  // #690005
        public static let errorContainer = Color(.sRGB, red: 0.576, green: 0, blue: 0.039, opacity: 1)  // #93000a
        public static let onErrorContainer = Color(.sRGB, red: 1, green: 0.855, blue: 0.839, opacity: 1)  // #ffdad6
        public static let primaryFixed = Color(.sRGB, red: 0.886, green: 0.886, blue: 0.886, opacity: 1)  // #e2e2e2
        public static let primaryFixedDim = Color(.sRGB, red: 0.776, green: 0.776, blue: 0.78, opacity: 1)  // #c6c6c7
        public static let onPrimaryFixed = Color(.sRGB, red: 0.102, green: 0.11, blue: 0.11, opacity: 1)  // #1a1c1c
        public static let onPrimaryFixedVariant = Color(.sRGB, red: 0.271, green: 0.278, blue: 0.278, opacity: 1)  // #454747
        public static let secondaryFixed = Color(.sRGB, red: 0.816, green: 0.894, blue: 1, opacity: 1)  // #d0e4ff
        public static let secondaryFixedDim = Color(.sRGB, red: 0.678, green: 0.788, blue: 0.922, opacity: 1)  // #adc9eb
        public static let onSecondaryFixed = Color(.sRGB, red: 0, green: 0.114, blue: 0.208, opacity: 1)  // #001d35
        public static let onSecondaryFixedVariant = Color(.sRGB, red: 0.176, green: 0.286, blue: 0.396, opacity: 1)  // #2d4965
        public static let tertiaryFixed = Color(.sRGB, red: 1, green: 0.847, blue: 0.906, opacity: 1)  // #ffd8e7
        public static let tertiaryFixedDim = Color(.sRGB, red: 1, green: 0.686, blue: 0.827, opacity: 1)  // #ffafd3
        public static let onTertiaryFixed = Color(.sRGB, red: 0.239, green: 0, blue: 0.149, opacity: 1)  // #3d0026
        public static let onTertiaryFixedVariant = Color(.sRGB, red: 0.522, green: 0.078, blue: 0.353, opacity: 1)  // #85145a
        public static let background = Color(.sRGB, red: 0.043, green: 0.075, blue: 0.149, opacity: 1)  // #0b1326
        public static let onBackground = Color(.sRGB, red: 0.855, green: 0.886, blue: 0.992, opacity: 1)  // #dae2fd
        public static let surfaceVariant = Color(.sRGB, red: 0.176, green: 0.204, blue: 0.286, opacity: 1)  // #2d3449
    }

    public enum Typography {
        public static let displayLg = Font.custom("Inter", size: 84).weight(.bold)
        public static let headlineLg = Font.custom("Inter", size: 32).weight(.semibold)
        public static let headlineMd = Font.custom("Inter", size: 24).weight(.medium)
        public static let bodyLg = Font.custom("Inter", size: 18).weight(.regular)
        public static let bodyMd = Font.custom("Inter", size: 16).weight(.regular)
        public static let labelSm = Font.custom("Inter", size: 12).weight(.semibold)
    }

    public enum Spacing {
        public static let unit: CGFloat = 8
        public static let containerPadding: CGFloat = 24
        public static let cardGap: CGFloat = 16
        public static let sectionMargin: CGFloat = 40
        public static let glassPadding: CGFloat = 20
    }

    public enum Radius {
        public static let sm: CGFloat = 0.25  // 0.25rem
        public static let dEFAULT: CGFloat = 0.5  // 0.5rem
        public static let md: CGFloat = 0.75  // 0.75rem
        public static let lg: CGFloat = 1  // 1rem
        public static let xl: CGFloat = 1.5  // 1.5rem
        public static let full: CGFloat = 9999
    }
}
