// SwiftUI theme exporter — emits a `Theme.swift` with Color/Font/CGFloat
// constants. The Apple-native replacement for the Tailwind exporter.

import Foundation

/// Generate Swift source for a strongly-typed `Theme` enum from the resolved model.
public func exportSwiftTheme(_ state: DesignSystemState, enumName: String = "Theme") -> String {
    var out = ""
    let title = state.name ?? "DESIGN.md"
    out += "// \(title) — generated by designmd. Do not edit.\n"
    out += "// Source of truth: DESIGN.md\n\n"
    out += "import SwiftUI\n\n"
    out += "public enum \(enumName) {\n"

    if state.colors.size > 0 {
        out += "    public enum Colors {\n"
        for (name, c) in state.colors {
            out += "        public static let \(ident(name)) = \(colorLiteral(c))  // \(c.hex)\n"
        }
        out += "    }\n\n"
    }

    if state.typography.size > 0 {
        out += "    public enum Typography {\n"
        for (name, t) in state.typography {
            out += "        public static let \(ident(name)) = \(fontLiteral(t))\n"
        }
        out += "    }\n\n"
    }

    if state.spacing.size > 0 {
        out += "    public enum Spacing {\n"
        for (name, d) in state.spacing {
            out += "        public static let \(ident(name)): CGFloat = \(dimLiteral(d))\n"
        }
        out += "    }\n\n"
    }

    if state.rounded.size > 0 {
        out += "    public enum Radius {\n"
        for (name, d) in state.rounded {
            out += "        public static let \(ident(name)): CGFloat = \(dimLiteral(d))\n"
        }
        out += "    }\n\n"
    }

    if out.hasSuffix("\n\n") { out.removeLast() }
    out += "}\n"
    return out
}

// ── Literals ───────────────────────────────────────────────────────

private func colorLiteral(_ c: ResolvedColor) -> String {
    let r = num(Double(c.r) / 255)
    let g = num(Double(c.g) / 255)
    let b = num(Double(c.b) / 255)
    if let a = c.a, a < 1 {
        return "Color(.sRGB, red: \(r), green: \(g), blue: \(b), opacity: \(num(a)))"
    }
    return "Color(.sRGB, red: \(r), green: \(g), blue: \(b), opacity: 1)"
}

private func dimLiteral(_ d: ResolvedDimension) -> String {
    // pt and px map straight to points; other units keep the numeric value with a note.
    if d.unit == "pt" || d.unit == "px" || d.unit.isEmpty {
        return num(d.value)
    }
    return "\(num(d.value))  // \(num(d.value))\(d.unit)"
}

private enum FontKind {
    case system(design: String?)  // nil = default design
    case custom(String)
}

private func fontLiteral(_ t: ResolvedTypography) -> String {
    let size = t.fontSize.map { num($0.value) } ?? "17"
    let weight = fontWeight(t.fontWeight)
    let family = t.fontFamily ?? ""

    switch fontKind(for: family) {
    case let .system(design):
        var call = "Font.system(size: \(size), weight: \(weight)"
        if let design { call += ", design: \(design)" }
        call += ")"
        return call
    case let .custom(name):
        return "Font.custom(\"\(name)\", size: \(size)).weight(\(weight))"
    }
}

private func fontKind(for family: String) -> FontKind {
    switch family.trimmingCharacters(in: .whitespaces).lowercased() {
    case "", "sf pro", "sf pro text", "sf pro display", "system", "-apple-system":
        return .system(design: nil)
    case "sf pro rounded":
        return .system(design: ".rounded")
    case "sf mono", "sf mono regular":
        return .system(design: ".monospaced")
    case "new york", "ny":
        return .system(design: ".serif")
    default:
        return .custom(family)
    }
}

private func fontWeight(_ w: Double?) -> String {
    switch w {
    case .some(100): return ".ultraLight"
    case .some(200): return ".thin"
    case .some(300): return ".light"
    case .some(400): return ".regular"
    case .some(500): return ".medium"
    case .some(600): return ".semibold"
    case .some(700): return ".bold"
    case .some(800): return ".heavy"
    case .some(900): return ".black"
    default: return ".regular"
    }
}

private func num(_ d: Double) -> String {
    if d.rounded() == d && abs(d) < 1e15 { return String(Int(d)) }
    return String(((d * 1000).rounded() / 1000))
}

// ── Identifier sanitization ────────────────────────────────────────

private let swiftKeywords: Set<String> = [
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func",
    "import", "init", "inout", "internal", "let", "open", "operator", "private",
    "protocol", "public", "rethrows", "static", "struct", "subscript", "typealias",
    "var", "break", "case", "continue", "default", "defer", "do", "else", "fallthrough",
    "for", "guard", "if", "in", "repeat", "return", "switch", "where", "while", "as",
    "catch", "false", "is", "nil", "self", "super", "throw", "throws", "true", "try", "Any",
]

/// Convert a token name (kebab/snake/spaced) to a camelCase Swift identifier.
func ident(_ name: String) -> String {
    let parts = name.split(whereSeparator: { $0 == "-" || $0 == "_" || $0 == " " }).map(String.init)
    guard let first = parts.first else { return "_" }
    var result = first.lowercasedFirst()
    for p in parts.dropFirst() { result += p.capitalizedFirst() }
    // Sanitize illegal characters.
    result = String(result.unicodeScalars.map { s -> Character in
        (s.properties.isAlphabetic || ("0"..."9").contains(Character(s))) ? Character(s) : "_"
    })
    if let f = result.first, f.isNumber { result = "_" + result }
    if swiftKeywords.contains(result) { return "`\(result)`" }
    return result.isEmpty ? "_" : result
}

private extension String {
    func lowercasedFirst() -> String {
        isEmpty ? self : prefix(1).lowercased() + dropFirst()
    }
    func capitalizedFirst() -> String {
        isEmpty ? self : prefix(1).uppercased() + dropFirst()
    }
}
