// Tide — generated by designmd. Do not edit.
// Source of truth: DESIGN.md

import SwiftUI

public enum Theme {
    public enum Colors {
        public static let primary = Color(.sRGB, red: 0.043, green: 0.239, blue: 0.322, opacity: 1)  // #0b3d52
        public static let accent = Color(.sRGB, red: 0, green: 0.627, blue: 0.776, opacity: 1)  // #00a0c6
        public static let surface = Color(.sRGB, red: 0.969, green: 0.976, blue: 0.984, opacity: 1)  // #f7f9fb
        public static let onSurface = Color(.sRGB, red: 0.043, green: 0.102, blue: 0.133, opacity: 1)  // #0b1a22
    }

    public enum Typography {
        public static let largeTitle = Font.system(size: 34, weight: .bold)
        public static let body = Font.system(size: 17, weight: .regular)
        public static let metric = Font.system(size: 13, weight: .medium, design: .monospaced)
    }

    public enum Spacing {
        public static let sm: CGFloat = 8
        public static let md: CGFloat = 16
    }

    public enum Radius {
        public static let md: CGFloat = 12
    }
}
